### PR TITLE
 Update versions of devDependencies in package.json

### PR DESCRIPTION
**Pull request by Vehmloewff**
Having your devDependencies up to date is usually good.

Fixes a security issue with `ws` required by `rollup-plugin-livereload`.  `rollup-plugin-livereload` rolled out a new patch version to fix this.

### CODE REVIEW

**Comment by YogliB** [comment]
Hey @Vehmloewff, thank you!

About the version updates, there's a bot that does that automatically, so there's no need to PR about this.
About the prettier config file, it's just my taste...

**Comment by Vehmloewff** [comment]
Oh, you're right!  Sorry about that!

**Comment by YogliB** [comment]
I suggest using [hub](https://github.com/github/hub) for your PRs, it really helped me.

**Comment by Vehmloewff** [comment]
Thanks, I'll look into that.

**Pull request closed without merging**
